networks:
  IdentityService: 
    driver: bridge
  ProfileService: 
    driver: bridge
  VacanciesService:
    driver: bridge
  ChatService:
    driver: bridge
  
  
services:
  api-gateway:
    image: api-gateway
    container_name: api-gateway
    build:
      context: .
      dockerfile: ./ApiGateway/Dockerfile
    working_dir: "/app"
    ports:
      - "5000:80"
    networks:
      - IdentityService
      - ProfileService
      - VacanciesService
      - ChatService
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - IdentityService
      - ProfileService
      - VacanciesService
  
  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq
      - ./rabbitmq-logs:/var/log/rabbitmq
    networks:
        - IdentityService
        - ProfileService
        - VacanciesService
        - ChatService
  
  identity-postgres:
    image: postgres
    container_name: identity-postgres
    ports:
      - "5431:5432"
    # restart: always
    environment:
      POSTGRES_USER: postgres_identity
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: IdentityDb
    volumes:
      - ./identityDbDir:/var/lib/postgresql/data
    networks:
      - IdentityService
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 3s
      retries: 3
        
  identity-service:
    image: identity-service
    container_name: identity-service
    build:
      context: .
      dockerfile: ./IdentityService/Dockerfile
    working_dir: "/app"
    # restart: always
    ports:
      - "5242:80"
    depends_on:
      identity-postgres:
        condition: service_healthy
    networks:
      - IdentityService
    
  profile-postgres:
    image: postgres
    container_name: profile-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres_profile
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ProfileDb
    # restart: always
    volumes:
        - ./profileDbDir:/var/lib/postgresql/data
    networks:
        - ProfileService
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 3s
      retries: 3
    
  profile-service:
    image: profile-service
    container_name: profile-service
    build:
      context: .
      dockerfile: ./ProfilesService/Dockerfile
    working_dir: "/app"
    # restart: always
    ports:
      - "5243:80"
    depends_on:
      profile-postgres:
        condition: service_healthy
    networks:
      - ProfileService
    
  vacancies-postgres:
    image: postgres
    container_name: vacancies-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres_vacancies
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: VacanciesDb
    # restart: always
    volumes:
        - ./vacanciesDbDir:/var/lib/postgresql/data
    networks:
        - VacanciesService
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready" ]
        interval: 10s
        timeout: 3s
        retries: 3
    
  vacancies-service:
    image: vacancies-service
    container_name: vacancies-service
    build:
      context: .
      dockerfile: ./VacanciesService/Dockerfile
    # restart: always
    working_dir: "/app"
    ports:
      - "5244:80"
    depends_on:
      vacancies-postgres:
        condition: service_healthy
    networks:
      - VacanciesService
  
  chat-postgres:
    image: postgres
    container_name: chat-postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres_chat
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ChatDb
    # restart: always
    volumes:
        - ./chatDbDir:/var/lib/postgresql/data
    networks:
        - ChatService
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready" ]
        interval: 10s
        timeout: 3s
        retries: 3
    
  chat-service:
    image: chat-service
    container_name: chat-service
    build:
      context: .
      dockerfile: ./ChatService/Dockerfile
    # restart: always
    working_dir: "/app"
    ports:
      - "5245:80"
    depends_on:
      chat-postgres:
        condition: service_healthy
    networks:
      - ChatService
      