apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-gateway
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/djinniclone-chatservice: "true"
        io.kompose.network/djinniclone-emailservice: "true"
        io.kompose.network/djinniclone-identityservice: "true"
        io.kompose.network/djinniclone-profileservice: "true"
        io.kompose.network/djinniclone-vacanciesservice: "true"
        io.kompose.service: api-gateway
    spec:
      containers:
        - image: dexon03/api-gateway
          imagePullPolicy: Always
          name: api-gateway
          ports:
            - containerPort: 80
              hostPort: 5000
              protocol: TCP
          resources: {}
          workingDir: /app
status: {}
