apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: chat-service
  name: chat-service
spec:
  ports:
    - name: "5245"
      port: 5245
      targetPort: 80
  selector:
    io.kompose.service: chat-service
status:
  loadBalancer: {}
