apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: chat-service
  name: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: chat-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/djinniclone-chatservice: "true"
        io.kompose.service: chat-service
    spec:
      containers:
        - image: dexon03/chat-service
          imagePullPolicy: Always
          name: chat-service
          ports:
            - containerPort: 80
              hostPort: 5245
              protocol: TCP
          resources: {}
          workingDir: /app
      restartPolicy: Always
status: {}
