apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: chat-postgres
  name: chat-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: chat-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/djinniclone-chatservice: "true"
        io.kompose.service: chat-postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: ChatDb
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres_chat
          image: postgres
          name: chat-postgres
          ports:
            - containerPort: 5432
              hostPort: 5434
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: chat-postgres-claim0
      restartPolicy: Always
      volumes:
        - name: chat-postgres-claim0
          persistentVolumeClaim:
            claimName: chat-postgres-claim0
status: {}
