apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: identity-postgres
  name: identity-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: identity-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/djinniclone-identityservice: "true"
        io.kompose.service: identity-postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: IdentityDb
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres_identity
          image: postgres
          name: identity-postgres
          ports:
            - containerPort: 5432
              hostPort: 5431
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: identity-postgres-claim0
      restartPolicy: Always
      volumes:
        - name: identity-postgres-claim0
          persistentVolumeClaim:
            claimName: identity-postgres-claim0
status: {}
