apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: profile-service
  name: profile-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: profile-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/djinniclone-profileservice: "true"
        io.kompose.service: profile-service
    spec:
      containers:
        - image: dexon03/profile-service
          imagePullPolicy: Always
          name: profile-service
          ports:
            - containerPort: 80
              hostPort: 5243
              protocol: TCP
          resources: {}
          workingDir: /app
      restartPolicy: Always
status: {}
