apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: profile-postgres
  name: profile-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: profile-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/djinniclone-profileservice: "true"
        io.kompose.service: profile-postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: ProfileDb
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres_profile
          image: postgres
          name: profile-postgres
          ports:
            - containerPort: 5432
              hostPort: 5432
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: profile-postgres-claim0
      volumes:
        - name: profile-postgres-claim0
          persistentVolumeClaim:
            claimName: profile-postgres-claim0
status: {}
