apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: vacancies-postgres
  name: vacancies-postgres
spec:
  ports:
    - name: "5433"
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: vacancies-postgres
status:
  loadBalancer: {}
