apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: vacancies-postgres
  name: vacancies-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vacancies-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/djinniclone-vacanciesservice: "true"
        io.kompose.service: vacancies-postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: VacanciesDb
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres_vacancies
          image: postgres
          name: vacancies-postgres
          ports:
            - containerPort: 5432
              hostPort: 5433
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: vacancies-postgres-claim0
      volumes:
        - name: vacancies-postgres-claim0
          persistentVolumeClaim:
            claimName: vacancies-postgres-claim0
status: {}
