apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: vacancies-service
  name: vacancies-service
spec:
  ports:
    - name: "5244"
      port: 5244
      targetPort: 80
  selector:
    io.kompose.service: vacancies-service
status:
  loadBalancer: {}
