apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: chat-db-storage-class
provisioner: pd.csi.storage.gke.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: pd-balanced
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chat-db-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 100Mi
      cpu: 50m
      
#---

#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: chat-db-persistent-volume
#spec:
#  capacity:
#    storage: 1Gi
#  accessModes:
#    - ReadWriteOnce
#  volumeMode: Filesystem
#  storageClassName: standard
#  hostPath:
#    path: /data/ChatDb
#    type: DirectoryOrCreate

#---
#
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: chat-db-persistent-volume-claim
#spec:
#  volumeName: chat-db-persistent-volume
#  storageClassName: standard
#  resources:
#    requests:
#      storage: 1Gi
#  accessModes:
#    - ReadWriteOnce