apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: identity-db-persistent-volume-claim
spec:
  volumeName: identity-db-persistent-volume
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
  accessModes:
      - ReadWriteOnce