apiVersion: v1
kind: Service
metadata:
  name: profile-service
spec:
  selector:
    app: profile-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service-deployment
  labels:
    app: profile-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-service
  template:
    metadata:
      name: profile-service
      labels:
        app: profile-service
    spec:
      containers:
        - name: profile-service
          image: dexon03/profile-service:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /app/PdfResumesFiles
              name: profile-service-dir
      volumes:
        - name: profile-service-dir
          persistentVolumeClaim:
            claimName: profile-service-persistent-volume-claim

