apiVersion: v1
kind: Service
metadata:
  name: profile-postgres
spec:
  selector:
    app: profile-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-postgres
  labels:
    app: profile-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-postgres
  template:
    metadata:
      name: profile-postgres
      labels:
        app: profile-postgres
    spec:
      containers:
        - name: profile-postgres
          image: postgres
          imagePullPolicy: Always
          env:
            - name: POSTGRES_USER
              value: postgres_profile
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: profileDb
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: profile-db-dir
          ports:
            - containerPort: 5432
              hostPort: 5432
              protocol: TCP
      volumes:
        - name: profile-db-dir
          persistentVolumeClaim:
            claimName: profile-db-persistent-volume-claim