apiVersion: v1
kind: PersistentVolume
metadata:
  name: profile-db-persistent-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: standard
  hostPath:
    path: /data/ProfileDb
    type: DirectoryOrCreate
  
  