apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-volume-claim
spec:
  volumeName: rabbitmq-persistent-volume
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
