apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
    - name: "5672"
      port: 5672
      targetPort: 5672
    - name: "15672"
      port: 15672
      targetPort: 15672
  selector:
    app: rabbitmq

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:management
          ports:
            - containerPort: 5672
              hostPort: 5672
              protocol: TCP
            - containerPort: 15672
              hostPort: 15672
              protocol: TCP
          env:
            - name: RABBITMQ_DEFAULT_PASS
              value: guest
            - name: RABBITMQ_DEFAULT_USER
              value: guest
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: rabbitmq-volume-claim
            - mountPath: /var/log/rabbitmq
              name: rabbitmq-logs-volume-claim
      hostname: rabbitmq
      restartPolicy: Always
      volumes:
        - name: rabbitmq-volume-claim
          persistentVolumeClaim:
            claimName: rabbitmq-volume-claim
        - name: rabbitmq-logs-volume-claim
          persistentVolumeClaim:
            claimName: rabbitmq-logs-volume-claim